# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0082_auto_20181231_1519'),
        ('registration', '0060_auto_20190722_0443'),
    ]

    operations = [
    ]
