# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 23:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    replaces = [('registration', '0084_auto_20190724_0518'), ('registration', '0085_auto_20190725_0506'), ('registration', '0086_auto_20190725_0715'), ('registration', '0087_auto_20190725_1707'), ('registration', '0088_order_lastfour')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('registration', '0083_merge_20190723_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendeeoptions',
            options={'verbose_name': 'Attendee option', 'verbose_name_plural': 'Attendee options'},
        ),
        migrations.AlterModelOptions(
            name='banlist',
            options={'verbose_name_plural': 'Ban list'},
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'Charities'},
        ),
        migrations.AlterModelOptions(
            name='dealerasst',
            options={'verbose_name': 'Dealer assistant', 'verbose_name_plural': 'Dealer assistants'},
        ),
        migrations.AlterModelOptions(
            name='priceleveloption',
            options={'verbose_name': 'Price level option', 'verbose_name_plural': 'Price level options (merchandise)'},
        ),
        migrations.AlterModelOptions(
            name='shirtsizes',
            options={'verbose_name_plural': 'Shirt sizes'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='maxAge',
            field=registration.models.IntegerRangeField(blank=True, help_text='Hide this level from anyone over this age by the first day of the event. (Blank to disable).', null=True, verbose_name='Maximum age'),
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='minAge',
            field=registration.models.IntegerRangeField(default=13, help_text='Attendee must be this old by first day of event to select this level', verbose_name='Minimum age required'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amountOff',
            field=models.DecimalField(decimal_places=2, help_text='Enter 0 if specifying a percentage to take off', max_digits=6, null=True, verbose_name='Amount off'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='codeName',
            field=models.CharField(max_length=100, verbose_name='Discount code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='endDate',
            field=models.DateTimeField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='oneTime',
            field=models.BooleanField(default=False, verbose_name='One-time use'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentOff',
            field=models.IntegerField(help_text='Enter 0 if specifying an amount to take off', null=True, verbose_name='Percent off'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='startDate',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerEmail',
            field=models.CharField(blank=True, default='registration@example.com', help_text='Email to display on error messages for dealer registration', max_length=200, verbose_name='Dealer Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrationEmail',
            field=models.CharField(blank=True, default='registration@example.com', help_text='Email to display on error messages for attendee registration', max_length=200, verbose_name='Registration Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staffEmail',
            field=models.CharField(blank=True, default='registration@example.com', help_text='Email to display on error messages for staff registration', max_length=200, verbose_name='Staff Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Badge'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Order'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='emailVIP',
            field=models.BooleanField(default=False, help_text='Send an email notification to the below address(es) when anyone registers at this level.', verbose_name='Email VIP notifications'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='emailVIPEmails',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of emails to send a notification to.', max_length=400, verbose_name='VIP notification emails'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='endDate',
            field=models.DateTimeField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='group',
            field=models.TextField(blank=True, help_text="'vip' is the only group we know about right now, shown in that report."),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='isMinor',
            field=models.BooleanField(default=False, help_text='(Legacy)'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='priceLevelOptions',
            field=models.ManyToManyField(blank=True, help_text='Select options or merchandise available as an add-on for this level', to='registration.PriceLevelOption', verbose_name='Level options'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='public',
            field=models.BooleanField(default=False, help_text='If unchecked, level is only available for the on-site form.'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='startDate',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='description',
            field=models.TextField(blank=True, help_text='HTML allowed'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionExtraType',
            field=models.CharField(blank=True, choices=[('bool', 'Checkbox'), ('int', 'Quantity'), ('string', 'Text'), ('plaintext', 'Label'), ('ShirtSizes', 'Shirt size')], default='bool', help_text='Form type to render', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionExtraType2',
            field=models.CharField(blank=True, choices=[('bool', 'Checkbox'), ('int', 'Quantity'), ('string', 'Text'), ('plaintext', 'Label'), ('ShirtSizes', 'Shirt size')], default='', help_text='(Unused)', max_length=100, verbose_name='Type 2'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionExtraType3',
            field=models.CharField(blank=True, choices=[('bool', 'Checkbox'), ('int', 'Quantity'), ('string', 'Text'), ('plaintext', 'Label'), ('ShirtSizes', 'Shirt size')], default='', help_text='(Unused)', max_length=100, verbose_name='Type 3'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionImage',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.content_file_name, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionName',
            field=models.CharField(max_length=200, verbose_name='Option name'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='rank',
            field=models.IntegerField(default=0, help_text='Numerical rank for ordering items in form (ascending)'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.CharField(blank=True, max_length=128, null=True, verbose_name='PIN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', help_text='Filename (without extension) for site theme CSS', max_length=256)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site option',
                'verbose_name_plural': 'Site options',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('issue_refund', 'Can issue refunds'), ('cash', 'Can handle cash transactions'), ('cash_admin', 'Can open and close cash drawer amounts (manager)'), ('discount', 'Can create discounts of arbitrary amount'))},
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastFour',
        ),
        migrations.AddField(
            model_name='event',
            name='attendeeCodeOfConduct',
            field=models.TextField(default='I agree to abide by the {{ event.name }} <a href="{{ event.codeOfConduct }}" target="_blank">Code of Conduct</a>', help_text='HTML template to show for attendee agreement checkbox.', verbose_name='Attendee agreement text'),
        ),
        migrations.AddField(
            model_name='event',
            name='dealerCodeOfConduct',
            field=models.TextField(default='I agree to abide by the {{ event.name }} <a href="{{ event.codeOfConduct }}" target="_blank">Code of Conduct</a>', help_text='HTML template to show for dealer agreement checkbox.', verbose_name='Dealer agreement text'),
        ),
        migrations.AddField(
            model_name='event',
            name='staffCodeOfConduct',
            field=models.TextField(default='I agree to abide by the {{ event.name }} <a href="{{ event.codeOfConduct }}" target="_blank">Code of Conduct</a>', help_text='HTML template to show for staff agreement checkbox.', verbose_name='Staff agreement text'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='aslRequest',
            field=models.BooleanField(default=False, verbose_name='ASL services requested'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='emailsOk',
            field=models.BooleanField(default=False, verbose_name='Add to mailing list'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='firstName',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='holdType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.HoldType', verbose_name='Hold type'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lastName',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='parentEmail',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parent email'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='parentFirstName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parent first name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='parentLastName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parent last name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='parentPhone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Parent phone'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='state',
            field=models.CharField(blank=True, max_length=200, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='surveyOk',
            field=models.BooleanField(default=False, verbose_name='Add to survey mailing list'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='volunteerContact',
            field=models.BooleanField(default=False, verbose_name='Interested in volunteering'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='volunteerDepts',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Volunteer department interests'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badgeName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Badge name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badgeNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Badge number'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='printCount',
            field=models.IntegerField(default=0, verbose_name='Badge print count'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='registeredDate',
            field=models.DateTimeField(null=True, verbose_name='Registered on'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='registrationToken',
            field=models.CharField(default=registration.models.getRegistrationToken, max_length=200, verbose_name='Registration token'),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(registration.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='agreeToRules',
            field=models.BooleanField(default=False, verbose_name='Agrees to Code of Conduct'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='artShow',
            field=models.BooleanField(default=False, verbose_name='Art show'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='businessName',
            field=models.CharField(max_length=200, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='charityRaffle',
            field=models.TextField(blank=True, verbose_name='Charity raffle'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='discountReason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discount reason'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='farFrom',
            field=models.CharField(blank=True, help_text='Requests to be placed far from this vendor', max_length=200, verbose_name='Far from'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='nearTo',
            field=models.CharField(blank=True, help_text='Requests to be placed near this vendor', max_length=200, verbose_name='Near to'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='needPower',
            field=models.BooleanField(default=False, verbose_name='Need power'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='needWifi',
            field=models.BooleanField(default=False, verbose_name='Need Wifi'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='registrationToken',
            field=models.CharField(default=registration.models.getRegistrationToken, max_length=200, verbose_name='Registration token'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='tableNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Table number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='tableSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.TableSize', verbose_name='Table size'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='wallSpace',
            field=models.BooleanField(default=False, verbose_name='Prefer wall-space'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='willSwitch',
            field=models.BooleanField(default=False, verbose_name='Will switch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='volunteerListOk',
            field=models.BooleanField(default=False, help_text='If checked, attendees can sign up to volunteer for this department', verbose_name='Add to volunteer list'),
        ),
        migrations.AlterField(
            model_name='event',
            name='codeOfConduct',
            field=models.CharField(blank=True, default='/code-of-conduct', help_text='Link to code of conduct agreement', max_length=500, verbose_name='Code of Conduct URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='default',
            field=models.BooleanField(default=False, help_text='The default event will be used as the basis for all current event configuration', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apiData',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingAddress1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingAddress2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingCity',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingCountry',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingEmail',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingPostal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Billing postal code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingState',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing state/province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billingType',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Credit', 'Credit'), ('Cash', 'Cash'), ('Comp', 'Comp')], default='Credit', max_length=20, verbose_name='Billing Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='charityDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Charity donation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orgDonation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Organization donation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='settledDate',
            field=models.DateTimeField(auto_now_add=True, help_text='(Deprecated)', null=True, verbose_name='Settled date'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='enteredBy',
            field=models.CharField(max_length=100, verbose_name='Entered by'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='enteredDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Entered date'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='priceLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.PriceLevel', verbose_name='Price level'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='checkedIn',
            field=models.BooleanField(default=False, verbose_name='Checked-in'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contactName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency contact name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency contact phone'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contactRelation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency contact relation'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='needRoom',
            field=models.BooleanField(default=False, verbose_name='Need room'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registrationToken',
            field=models.CharField(default=registration.models.getRegistrationToken, max_length=200, verbose_name='Registration token'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shirtsize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.ShirtSizes', verbose_name='Shirt size'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialFood',
            field=models.TextField(blank=True, verbose_name='Dietary restrictions'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialMedical',
            field=models.TextField(blank=True, verbose_name='Medical considerations'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialSkills',
            field=models.TextField(blank=True, verbose_name='Special skills'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='timesheetAccess',
            field=models.BooleanField(default=False, verbose_name='Timesheet access'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='chairMax',
            field=models.IntegerField(default=1, verbose_name='Maximum chairs'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='chairMin',
            field=models.IntegerField(default=1, verbose_name='Minimum chairs'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='partnerMax',
            field=models.IntegerField(default=1, verbose_name='Maximium partners'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='partnerMin',
            field=models.IntegerField(default=1, verbose_name='Minimum partners'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='tableMax',
            field=models.IntegerField(default=0, verbose_name='Maximum tables'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='tableMin',
            field=models.IntegerField(default=0, verbose_name='Minimum tables'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendeeRegStart',
            field=models.DateTimeField(help_text='Start time for standard /registration form', verbose_name='Attendee Registration Start'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apiData',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lastFour',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
