# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_auto_20190724_0518_squashed_0088_order_lastfour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. VA for Virginia', max_length=128, null=True, verbose_name='Event location'),
        ),
    ]
