# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 04:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('registration', '0085_event_location'), ('registration', '0086_auto_20190725_2218')]

    dependencies = [
        ('registration', '0084_auto_20190724_0518_squashed_0088_order_lastfour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. VA for Virginia', max_length=128, null=True, verbose_name='Event location'),
        ),
        migrations.AddField(
            model_name='order',
            name='jsonData',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='url',
            field=models.CharField(help_text='Charity link', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apiData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
