# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 02:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0085_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jsonData',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='url',
            field=models.CharField(help_text='Charity link', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apiData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
