# Generated by Django 2.2.3 on 2019-07-26 09:41

import json

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

def copy_carts(apps, schema_editor):
    Cart = apps.get_model('registration', 'Cart')
    for cart in Cart.objects.all():
        try:
            cart.formJSON = json.loads(cart.formData)
        except TypeError:
            print("warn: unable to serialize formData field (id={0}).".format(cart.id))

        try:
            cart.headersJSON = json.loads(cart.formHeaders)
        except TypeError:
            print("warn: unable to serialize formHeaders field (id={0}).".format(cart.id))

        cart.save()

def reverse_migration(apps, schema_editor):
    Cart = apps.get_model('registration', 'Cart')
    for cart in Cart.objects.all():
        try:
            cart.formData = json.dumps(cart.formJSON)
        except TypeError:
            warn("warn: unable to reverse migration on id={0}.".format(cart.id))

        try:
            cart.formHeaders = json.dumps(cart.headersJSON)
        except TypeError:
            warn("warn: unable to reverse migration on id={0}.".format(cart.id))

        cart.save()



class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0085_event_location_squashed_0086_auto_20190725_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='formJSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='headersJSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='formData',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='formHeaders',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(copy_carts, reverse_migration),
    ]
